services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        ports:
            - 9000:9000
        depends_on:
            - mysql
        container_name: market_php

    nginx:
        build:
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - php
        container_name: market_nginx

    mysql:
        build:
            dockerfile: ./docker/mysql/Dockerfile
        image: mysql:9.1.0
        #restart: unless-stopped
        volumes:
            - market_mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: localPass
            MYSQL_DATABASE: market_db
            MYSQL_CHARSET: utf8mb4
            MYSQL_COLLATION: utf8mb4_unicode_ci
            #MYSQL_USER=admin
            #MYSQL_PASSWORD=root
        ports:
            - 3306:3306
        container_name: market_mysql

volumes:
    market_mysql_data:
